name: Deploy To-Do API

on:
  push:
    paths:
      - 'lambda_fn/**'
      - 'terraform/**'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:   ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:          ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform/envs/dev
          terraform init

      - name: Terraform Validate & Fmt
        run: |
          cd terraform/envs/dev
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform/envs/dev
          terraform plan -out tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform/envs/dev
          terraform apply -auto-approve tfplan
