name: Deploy To-Do API

on:
  push:
    paths:
      - 'lambda_fn/**'
      - 'terraform/**'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:   ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region:          ${{ env.AWS_REGION }}

      - name: Build Lambda artifact
        working-directory: lambda_fn
        run: |
          mkdir -p ../build
          zip -r ../build/todo.zip todo_handler.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Validate & Fmt
        working-directory: terraform/envs/dev
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan -out tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve tfplan
